name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Simulate changes
      shell: bash
      run: |
        cp LICENSE test1
        cp CHANGELOG.md test2
    - name: Store test archive
      uses: actions/cache/save@v3
      with:
        path: |
          test1
          test2
        key: shelved-changes-${{ github.sha }}
    - name: Clear changes
      shell: bash
      run: rm test1 test2
    - name: Test
      id: test
      uses: ./
      with:
        files: |
          test1
          test2
    - name: Check changes
      shell: bash
      run: |
        if [[ ! -f "test1" ]]; then
          echo "test1 not restored"
          exit 1
        fi
        if [[ ! -f "test2" ]]; then
          echo "test2 not restored"
          exit 1
        fi
