name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        cp LICENSE test1
        cp CHANGELOG.md test2
      shell: bash
    - uses: actions/cache/save@v4
      with:
        path: |
          test1
          test2
        key: shelved-changes-${{ github.sha }}
    - run: rm test1 test2
      shell: bash
    - uses: ./
      id: test
      with:
        files: |
          test1
          test2
    - run: |
        if [[ ! -f "test1" ]]; then
          echo "test1 not restored"
          exit 1
        fi
        if [[ ! -f "test2" ]]; then
          echo "test2 not restored"
          exit 1
        fi
      shell: bash
    - uses: prantlf/publish-release-action@v1
      if: ${{ github.ref_name == 'master' }}
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
